### ISSUE TITLE
Tables should be accessible by links WITHOUT username

### ISSUE THREAD

**Issue by RogerTangos** [datahuborg/datahub#28]
I would like to be able to link people to tables/repositories without using their usernames:

for example, instead of 
`https://datahub.csail.mit.edu/browse/USERNAME/REPONAME/table/TABLENAME`

use this and have username inferred by their login status.
`https://datahub.csail.mit.edu/browse/REPONAME/table/TABLENAME`

This is a thing that kept bugging me during getfit.

**Comment by karger** [comment]
I'm not entirely sure of the rationale for this.  Perhaps it is to 
support having an "anonymous" link that people can click on to be taken 
to their own table?

But this relies on the assumption that everyone using a particular app 
(like getfit) is going to have exactly the same repo name and table name 
for the app.  I don't think this can be relied on long term; rather, 
users need to be able to specify which arbitrarily named table in which 
arbitrarily named repo they are using with the app.  The reason for this 
is that otherwise two different apps might claim the same repo/table 
name, preventing the user from using both apps.

**Comment by RogerTangos** [comment]
This is a result of the openPDS model. More generally, the need is for

a) a way for users to be directed to tables within a schema.
b) a way for users to execute trusted pre-written DML statements.

The anonymous aspect of it isn't important. In the Getfit case, when trying
to provide instructions to n users with identical schemas, it wasn't
practical to generate n unique links.

I often found myself telling users to "log into datahub.csail.mit.edu,
click the 'getfit' repository, enter the below text into the box that says
'Type SQL here', and press run.

`--some sql statement for them to execute`

Even without using an openPDS model, it would still be useful to have some
way to direct users to "their" "tables" (actually views of shared tables)
and select from them.



Albert Carter

Programmer
Big Data Initiative
CSAIL, MIT

**Comment by abhardwaj** [comment]
This is by design.

The reason is that as a logged in user I might be interested in viewing
someone else's (say samm) repo and we want a consistent way to do it so any
repository is /browse/<user-name>/<repo-name>. Also, you might be a part of
multiple organizations and thus just /browse/<repo-name> would cause
ambiguity in case  same repo-name exists under two different organizations
you are part of.

-- anant

**Comment by sirrice** [comment]
If it's to promote laziness/ease-of-use maybe vanity urls is a solution.

**Comment by RogerTangos** [comment]
Vanity urls, or adding a value for the currently logged in user would work.

/browse/<logged-in-user>/<repo-name>

**Comment by RogerTangos** [comment]
Resolved in c26d7f20cb2b15f366d7ad05755533920d3e46ae
