### ISSUE TITLE
Allow users to share queries via GET statements

### ISSUE THREAD

**Issue by RogerTangos** [datahuborg/datahub#83]
Allow users to share query URLs with each other. Related to #82

**Comment by RogerTangos** [comment]
There's not a "share this query" button, but this is now possible via c26d7f20cb2b15f366d7ad05755533920d3e46ae.

/browse/user/REPONAME/query?q=

**Comment by RogerTangos** [comment]
Nevermind - reopening. We'd rather not allow this via a link.

**Comment by karger** [comment]
will the url in the address bar when i'm viewing the results be the url
I should share?

**Comment by karger** [comment]
why?  i think this is a good idea.

**Comment by RogerTangos** [comment]
I think it's still a good idea to have. The implementation I had allowed a user to send you a link, which contained arbitrary SQL to be executed. A safer implementation would be to present users with a page that pre-populated the SQL, and then let them hit run.

**Comment by karger** [comment]
actually, this suggests an interesting permissions issue. definitely a
bad idea to permit someone to send me a link that causes arbitrary
(destructive, possibly heavy load) computation to be executed when I
click---easy to cause me to destroy my own data.  But I should be able
to set up a "canned" query and release a url that causes that canned
query to be executed and results shown---since that will have various
useful applications.   If I'm releasing the link and I want the query to
execute over my tables as me, then I should be able to release that
link. On the other hand, what if I want to share a link that acts on the
*clicking user's* table?  that could also be useful ("here's a query to
clean up your address table").  But, it shouldn't execute when
clicked---clicking should take me to page asking if I want to permit the
query to execute. 

This is all related to the function cloud.

**Comment by RogerTangos** [comment]
Closed in 1b2764645424212215bfec7c13718a3194a45797.

This is a fix that uses DataHub's current templating/request framework. Once the REST branch integrated, we'll want to switch to that and django forms. Any refactor here will be part of a larger refactor of the templating system and src/browser.
